port: 9001
relay_port: 9000
api_path: http://localhost:9001/upload
stream_base: http://localhost:9001/stream
download_base: http://localhost:9001/download
media_storage_dir: ./local/uploads/original
stream_storage_dir: ./local/uploads/stream
wav_storage_dir: ./local/uploads/wav
stream_ffmpeg: ffmpeg
stream_chunk_size_seconds: 5
nostr_relay_db_file: relay.db
nostr_relay_port: 9000
db_file: sqlite.db
max_upload_size_mb: 40
accepted_mimetypes:
  - audio/wav
  - audio/wave
  - audio/x-wav
  - audio/mp3
  - audio/mpeg
  - audio/mpeg3
  - audio/x-mpeg-3
  - audio/mp4
  - audio/m4a
  - audio/aiff
  - audio/x-aiff
