port: 9001
api_host: http://localhost:9001
cdn_host: https://cdn.stemstr.app
s3_bucket: stemstr-media
max_upload_size_mb: 40
accepted_mimetypes:
  - audio/wav
  - audio/wave
  - audio/x-wav
  - audio/mp3
  - audio/mpeg
  - audio/mpeg3
  - audio/x-mpeg-3
  - audio/mp4
  - audio/m4a
  - audio/aiff
  - audio/x-aiff
  - audio/ogg
  - audio/flac
stream_ffmpeg: ffmpeg
stream_chunk_size_seconds: 5

nostr_relay_port: 9000
nostr_relay_info_pubkey: ~
nostr_relay_info_contact: ~
nostr_relay_info_description: custom relay for https://stemstr.app
nostr_relay_info_version: 0.1
nostr_relay_database_url: "postgresql://admin:password@localhost:5432/relay?sslmode=disable"
