port: 9001
api_path: http://localhost:9001/upload
stream_base: https://cdn.stemstr.app/stream
download_base: http://localhost:9001/download
media_storage_dir: ./local/uploads/original
stream_storage_dir: ./local/uploads/stream
wav_storage_dir: ./local/uploads/wav
stream_ffmpeg: ffmpeg
stream_chunk_size_seconds: 5
max_upload_size_mb: 40
db_file: sqlite.db
s3_bucket: stemstr-media
accepted_mimetypes:
  - audio/wav
  - audio/wave
  - audio/x-wav
  - audio/mp3
  - audio/mpeg
  - audio/mpeg3
  - audio/x-mpeg-3
  - audio/mp4
  - audio/m4a
  - audio/aiff
  - audio/x-aiff
  - audio/ogg
  - audio/flac

nostr_relay_port: 9000
nostr_relay_info_pubkey: ~
nostr_relay_info_contact: ~
nostr_relay_info_description: custom relay for https://stemstr.app
nostr_relay_info_version: 0.1
database_url: "postgresql://admin:password@localhost:5432/relay?sslmode=disable"
