version: "3.9"
services:
  api:
    build: "."
    command: "-config /config/api-config.yml"
    restart: on-failure:5
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./local:/config
