port: 9001
api_path: http://localhost:9001/upload
media_path: http://localhost:9001
accepted_mimetypes:
  - image/jpg
  - image/png
  - image/gif
  - video/mp4
  - audio/wave
storage_type: filesystem
storage_config:
  media_dir: ./files
max_upload_size_mb: 40
allow_violent_content: false
allow_adult_content: false
names:
  alice: npub1xxx
  bob: npub1yyy
